<a href="https://colab.research.google.com/github/Mutt108/An-lisis-exploratorio-de-datos/blob/main/Parcial_Andr%C3%A9s_Obando.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
plants = pd.read_csv("edible_plants.csv")

In [9]:
plants.head(8)

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
0,Pisum sativum,Pea,Legume,Full sun,Very High,6.0,7.5,Medium,Loamy,Annual,Half hardy,24,4-24,6,55-75,"A good source of vitamin K, manganese, and die...",80.0,Drought intolerant,"The pea is the small spherical seed, or the se...","Require a sunny, nutrient-rich, moisture-reten..."
1,Phaseolus coccineus,Beans (Runner),Legume,Full sun,Medium,6.0,6.8,Medium,Loamy and clay,Annual,Tender,26,16-30,7,65-85,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,Runner bean plants are more productive than gr...,"Beans are a tender, warm-weather crop. They ar..."
2,Phaseolus vulgari,Beans (French),Legume,Full sun,Medium,6.0,7.5,Medium,Any well-drained and fertile,Annual,Tender,26,16-30,7,40-55,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,"French beans are the unripe fruit, and protect...","Beans are a tender, warm-weather crop. They ar..."
3,Vicia faba,Beans (Broad),Legume,Full sun/partial shade/full shade,Very Low,6.0,7.0,Medium,Any well-drained and fertile,Annual,Hardy,10,8-15,7,85-115,"A good source of vitamin-B6 (pyridoxine), thia...",88.0,Drought intolerant,Broad beans - also known as the fava bean - ar...,Broad beans are a cool weather crop. They grow...
4,Brassica oleracea,Cabbage (Spring),Legume,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,55-85,"A very good source of manganese, dietary fibre...",25.0,Particularly vulnerable to pests. Do not grow ...,Cabbages are a leafy green or purple biennial ...,Cabbage is a cool-season crop best planted in ...
5,Brassica oleracea (Italica group),Broccoli,Brassica,Full sun/partial shade,Medium,6.0,7.5,High,Loamy and sandy,NaN,Half hardy,30,7-30,4,55-85,"A good source of vitamin C, folate, dietary fi...",34.0,A cool weather crop best not grown over hot su...,Broccoli is a member of the cabbage family. Th...,"Broccoli grow best in partial-shade, in firm, ..."
6,Brassica oleracea (Gemmifera group),Brussels Sprouts,Brassica,Full sun,Medium,6.0,7.5,High,Loamy,biennial,Hardy,26,7-30,4,180-,"A good source of dietary fibre, vitamin c, and...",35.0,Affected by a wide range of pests and diseases...,Brussels sprouts are a member of the cabbage f...,Brussels sprouts are a cool-season crop. They ...
7,Brassica oleracea (Botrytis group),Cauliflower,Brassica,Full sun,Medium,5.5,7.5,High,Any well-drained and fertile,NaN,Hardy,26,15-20,5,55-110,"A good source of vitamin C, vitamin K, and fol...",31.0,Sensitive to temperatures over 25 °C.,Cauliflower is a variety of common cabbage in ...,"Cauliflower grow best in partial-shade, in fir..."

In [10]:
plants.shape #Hay 140 filas y 20 columnas

(140, 20)

In [11]:
plants.shape[0] #Hay 140 filas

140

In [12]:
print(plants["common_name"].dtype) #Es tipo objeto, o sea es texto

object

In [13]:
plants["temperature_germination"].count() #Hay 104 valores no nulos

np.int64(104)

In [14]:
series_cultivation = plants["cultivation"]

sub = plants[["taxonomic_name", "cultivation", "temperature_class"]]

#Una series es una estructura que solo tiene una columna de datos con su índice, por otro lado, un dataframe es una estructura que tiene filas y columnas con datos y un índice

In [15]:
plants.iloc[2:8,2:5]

  cultivation                           sunlight     water
2      Legume                           Full sun    Medium
3      Legume  Full sun/partial shade/full shade  Very Low
4      Legume                           Full sun      High
5    Brassica             Full sun/partial shade    Medium
6    Brassica                           Full sun    Medium
7    Brassica                           Full sun    Medium

In [16]:
plants.loc[40:44, ["common_name", "water", "nutrients"]]

                   common_name   water nutrients
40                      Garlic  Medium       Low
41                      Ginger    High    Medium
42                    Kohlrabi  Medium    Medium
43                        Leek  Medium    Medium
44  Lettuce (Lambs/Corn Salad)    High    Medium

In [17]:
f1 = plants[plants["cultivation"]=="Cucurbit"]
len(f1) #Quedan 8 filas

8

In [18]:
f2 = plants[(plants["sunlight"]== "Full sun/partial shade") & (plants["water"]=="Medium")]
len(f2) #Quedan 34 filas

34

In [19]:
f3 = plants.loc[plants["preferred_ph_upper"]<=6.5, ["common_name", "preferred_ph_upper"]]
len(f3) #Cumplen 19 filas

19

In [20]:
f4 = plants.loc[plants["cultivation"].isin(["Brassica", "Legume"]), ["common_name", "cultivation"] ]
len(f4) #Cumplen 31 filas

31

In [21]:
f5 = plants[plants["common_name"].str.contains("berry", case =False, na = False)]
len(f5) #Cumplen 8 filas

8

In [22]:
f6 = plants[~(plants["nutrients"] == "Low")]
len(f6) #Quedan 92 filas

92

In [23]:
len(f6) + len((plants[plants['nutrients'] == 'Low'])) == len(plants)

True